### PR TITLE
Enhancement

### PR DESCRIPTION
**Pull request by Samriddhi25**
various icons and logo image updated #7

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Please share screenshot of the change you have made.

**Comment by Samriddhi25** [comment]
> Please share screenshot of the change you have made.
This file has the basic changes 
[ScreenshotBOSSY.docx](https://github.com/sharmaaditya570191/BossY/files/4277332/ScreenshotBOSSY.docx)

**Comment by sharmaaditya570191** [comment]
Looks great. Can you change the design at the top/

**Comment by Samriddhi25** [comment]
That's the place for the logo so should I add some random image or should I design a logo ?

**Comment by sharmaaditya570191** [comment]
Closing this as redundant.

**Pull request closed without merging**
