### PR TITLE
Added API Documentation for all routes

### PR DESCRIPTION
**Pull request by Endowmissy**
Solves issue #1 
@sharmaaditya570191 kindly review

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Nice work @Endowmissy . Just a few formatting - please arrange the status codes in bullets instead of writing them in the same line.

**Comment by Endowmissy** [comment]
Okay noted,will do that

**Comment by Endowmissy** [comment]
@sharmaaditya570191 I have rearranged the status codes as requested, please review
Attached are the screenshots of the request-response with morgan tiny
Get requests
Get id

**Comment by sharmaaditya570191** [comment]
Thanks for working on this @Endowmissy .

**Pull request merged**
