### PR TITLE
Changed the Color theme to lighter color

### LINKED ISSUE #60: Change the colour theme to somewhat lighter/brighter colour
Change the colour theme to somewhat lighter/brighter colour which will become day mode.

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fixes #60 
**Description
Changed the color theme of the website.

**Attaching the screenshot below:
image

### CODE REVIEW

**Comment by somyaranjan26** [comment]
Hey, can you also change the font and Icons and also make sure that app should cover around 80% of view/page right now the contents are in the center. try to resize the content and utilise whole view/page.

**Comment by shreyakapoor08** [comment]
> Hey, can you also change the font and Icons and also make sure that app should cover around 80% of view/page right now the contents are in the center. try to resize the content and utilise whole view/page.

I have changed the fonts and the icons as well. Please check

**Comment by somyaranjan26** [comment]
> I have changed the fonts and the icons as well. Please check

Can you share some screenshots

**Comment by shreyakapoor08** [comment]
image

image

image

**Comment by shreyakapoor08** [comment]
@sharmaaditya570191 Kindly check this PR

**Comment by somyaranjan26** [comment]
> @sharmaaditya570191 Kindly check this PR

@shreyakapoor08, right now we are finalising some UI/UX templates for this project. 
If you have any suggestions for Designs, let as know.

and soon we will attach the Image of the template.

**Comment by shreyakapoor08** [comment]
@somyaranjan so this color theme won't be added?

**Comment by shreyakapoor08** [comment]
Hi, any update on this pr?

**Pull request merged**
