### PR TITLE
created schema of Work using mongoose

### PR DESCRIPTION
**Pull request by BhuwanChandra**
fixes: #72 

@sharmaaditya570191 @somyaranjan26 please review the PR.

### CODE REVIEW

**Comment by suhanichawla** [comment]
Please modify the model according to createWork function in server/db.js

**Comment by BhuwanChandra** [comment]
I have updated the model according to createWork function in server/db.js

**Comment by suhanichawla** [comment]
@BhuwanChandra You just needed to replace priority with hours.
Rest everything was alright.
Should've mentioned that in my last comment. Please just make that change in your first commit.

**Comment by BhuwanChandra** [comment]
@suhanichawla I have done it now correctly.

**Pull request merged**
