### PR TITLE
fixes #98

### LINKED ISSUE #98: Create 5th page content component
You have to create a function component to replicate the following using React:-  
image  
Use `svg` format and `scss` for styling.

### PR DESCRIPTION
**Pull request by Geesa-Vihara**
5th Page Content Component
Path to component - localhost:3000/#/fifthPage
Progress Bar and Image implemented with animations
Installed node-sass for scss

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Please try resolving the conflicts as a bunch of PR's have been merged recently. Thanks.

**Comment by Geesa-Vihara** [comment]
> 
> 
> Please try resolving the conflicts as a bunch of PR's have been merged recently. Thanks.

@sharmaaditya570191 Resolved the conflicts. Can you kindly check on it and merge?

**Comment by sharmaaditya570191** [comment]
Can you please share screenshot of the UI?

**Comment by Geesa-Vihara** [comment]
> 
> 
> Can you please share screenshot of the UI?

Sure @sharmaaditya570191 
screenshot

**Pull request merged**
