### PR TITLE
Created login and signup page.

### PR DESCRIPTION
**Pull request by imrishabh18**
I have created the login and signup page with proper routing. But connecting it with database during signup  and authenticating when the user login's feature is still left. You can create a new issue for that.

### CODE REVIEW

**Comment by sharmaaditya570191** [comment]
Please attach a screenshot of the component you made. Thanks.

**Comment by imrishabh18** [comment]
Screenshot

Screenshot (1)

**Comment by sharmaaditya570191** [comment]
Looks good but please correct the alignment a bit. Thanks.

**Comment by imrishabh18** [comment]
I hope this works.

Screenshot (2)

**Comment by sharmaaditya570191** [comment]
Please try fixing the merge conflicts. Also we do not use `<br>` tags for spacing. Instead use css for that purpose so that the classes are reusable in case of same situation elsewhere.

**Comment by imrishabh18** [comment]
@sharmaaditya570191 I am not able get where to resolve conflicts ? As i have already made other PR's 
in other branches. Can you help me out from this ?

**Comment by sharmaaditya570191** [comment]
You have made some minor typos in ` src/components/MinionEdit.js`. Please fix them and don't link the `login` and `signup` component anywhere. For now jsut leave them as individual components. We will open new issues for linking them. Also please fix merge conflicts as I have merged some PR's recently. Thanks for your contribution.

**Comment by sharmaaditya570191** [comment]
Also don't have the `signup` page in the same PR. Open another issue for the `signup` page and I will assign you to it since you have already made the page.

**Comment by imrishabh18** [comment]
Okay

**Comment by sharmaaditya570191** [comment]
Marked

**Comment by sharmaaditya570191** [comment]
Lots of PR's have been merged and this design has become obsolete. Thank you for your contributions. If you want you can create a fresh PR with update design.

**Pull request closed without merging**
