### PR TITLE
Error in package.json

### PR DESCRIPTION
**Pull request by Adyasha8105**
Fixes #XX

**Description**

**Other information**

**Checklist:**
- [ ] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

### CODE REVIEW

**Comment by aashimgarg** [comment]
Dont copy my code @Adyasha8105

**Comment by Adyasha8105** [comment]
> Dont copy my code @Adyasha8105

Btw don't copy my code, I have already made a Pr on it.

**Comment by aashimgarg** [comment]
> > Dont copy my code @Adyasha8105
> 
> Btw don't copy my code, I have already made a Pr on it.

Cool Html file in React hahah

**Comment by Adyasha8105** [comment]
> > > Dont copy my code @Adyasha8105
> > 
> > 
> > Btw don't copy my code, I have already made a Pr on it.
> 
> Cool Html file in React hahah

haha it is in react

**Comment by sharmaaditya570191** [comment]
Remove old commits.

**Pull request closed without merging**
